from datetime import datetime, timedelta

import geopandas as gpd
import numpy as np
import pandas as pd
from scipy.spatial import cKDTree
from scipy.stats import skew

from Helpers.municiples import load_municipalities_as_points
from Helpers.season import season_start_of

STEP_DAYS = 2
FLOOR_DAYS = 20

# Grid cells sit 0.1 degrees apart, so anything beyond this means the
# municipality has no nearby precipitation data.
MAX_DIST_DEGREES = 0.15

enso_phases = {
    2004: "El Niño",
    2005: "Neutro",
    2006: "El Niño",
    2007: "La Niña",
    2008: "La Niña",
    2009: "El Niño",
    2010: "La Niña",
    2011: "La Niña",
    2012: "Neutro",
    2013: "Neutro",
    2014: "El Niño",
    2015: "El Niño",
    2016: "El Niño",
    2017: "Neutro",
    2018: "La Niña",
    2019: "Neutro",
    2020: "La Niña",
    2021: "La Niña",
    2022: "La Niña",
    2023: "El Niño",
    2024: "La Niña",
    2025: "La Niña",
    2026: "El Niño",
}


def map_points_to_segment(
    points: gpd.GeoDataFrame,
    precipitation: pd.DataFrame,
    lat_col: str,
    lon_col: str,
    id_col: str,
) -> gpd.GeoDataFrame:
    """
    Attach the nearest precipitation grid cell to each point.
    """
    # create a grid with the coordinates for each segment_id
    grid = (
        precipitation[["segment_id", "latitude", "longitude"]]
        .drop_duplicates("segment_id")
        .reset_index(drop=True)
    )

    # find the nearest neighbor using a cKDTree - k = 1 -> one neighbor
    tree = cKDTree(grid[["latitude", "longitude"]].to_numpy())
    dist, idx = tree.query(points[[lat_col, lon_col]].to_numpy(), k=1)

    out = points.copy()

    # query returns positions in `grid`, not segment_ids.
    out["segment_id"] = grid["segment_id"].to_numpy()[idx]

    # keeps the distance so the mapping can be sanity-checked below
    out["dist_grau"] = dist

    # check if any municipality is far from a segment_id
    far = out[out["dist_grau"] > MAX_DIST_DEGREES]
    if not far.empty:
        print(f"{len(far)} points far from the grid: {far[id_col].tolist()[:10]}")

    return out


def load_data(prec_path: str) -> tuple[gpd.GeoDataFrame, pd.DataFrame]:
    """
    Load the data generated by the DAGs.
    """
    prec = pd.read_csv(prec_path, sep=";")
    prec["date_precipitation"] = pd.to_datetime(prec["date_precipitation"])

    # The trained model expects columns named after occurrences
    municipalities = load_municipalities_as_points(
        lat_col="ocorrencia_latitude", lon_col="ocorrencia_longitude"
    )

    # attach each municipality to the nearest precipitation grid cell
    municipalities = map_points_to_segment(
        municipalities,
        prec,
        "ocorrencia_latitude",
        "ocorrencia_longitude",
        "municipio",
    )

    return municipalities, prec


def group_and_compute_skew(list_: list, group_size: int) -> float:
    grouped = [sum(list_[i : i + group_size]) for i in range(0, len(list_), group_size)]

    if len(set(grouped)) <= 1 or np.std(grouped) < 1e-8:
        return 0.0
    return skew(grouped)


def analyze_distribution(
    instance: dict,
    prec: pd.DataFrame,
    season_start: datetime,
    base_date: datetime,
) -> None:
    """
    Compute the rainfall distribution features for a single instance,
    covering the period from the start of the season up to base_date.
    """
    rainfall = prec[
        (prec["date_precipitation"] >= season_start)
        & (prec["date_precipitation"] <= base_date)
    ]["prec"].tolist()

    if not rainfall:
        raise ValueError(
            f"No precipitation data between {season_start:%Y-%m-%d} "
            f"and {base_date:%Y-%m-%d}"
        )

    total_rainfall = sum(rainfall)
    if total_rainfall > 0:
        normalized_rainfall = [v / total_rainfall for v in rainfall]
    else:
        normalized_rainfall = [0] * len(rainfall)

    dispersion = np.std(rainfall)
    peak = int(np.argmax(rainfall))
    asymmetry = group_and_compute_skew(normalized_rainfall, 4)
    median = np.median(rainfall)
    mode = max(set(rainfall), key=rainfall.count)

    if np.mean(rainfall) > 0:
        variation_coefficient = np.std(rainfall) / np.mean(rainfall)
    else:
        variation_coefficient = 0

    rainfall_array = np.array(rainfall)
    instance["chuva_dispersao"] = dispersion
    instance["chuva_pico_intervalo"] = peak
    instance["chuva_pico_valor"] = rainfall[peak]
    instance["chuva_assimetria"] = asymmetry
    instance["chuva_mediana"] = int(np.argmin(np.abs(rainfall_array - median)))
    instance["chuva_mediana_valor"] = median
    instance["chuva_moda"] = np.where(rainfall_array == mode)[0][0]
    instance["chuva_moda_valor"] = mode
    instance["prec_acumulada"] = total_rainfall
    instance["dias_chuva"] = sum(1 for v in rainfall if v > 0.5)
    instance["dia_da_safra"] = (base_date - season_start).days + 1
    instance["chuva_coeficiente_variacao"] = variation_coefficient
    instance["chuva_media"] = np.mean(rainfall)


def generate_instances_for_core(
    row,
    precipitation: pd.DataFrame,
    base_date: pd.Timestamp,
) -> list:
    """
    Generate the rows of a single core: from the start of the season plus
    FLOOR_DAYS up to base_date, one row every STEP_DAYS.
    """
    instances = []

    segment_id = row.segment_id
    season_start = season_start_of(base_date)
    prec_segment = precipitation[precipitation["segment_id"] == segment_id]

    current_date = season_start + timedelta(days=FLOOR_DAYS)

    while current_date <= base_date:
        instance = row._asdict()
        instance["data"] = current_date

        analyze_distribution(instance, prec_segment, season_start, current_date)

        # ENSO phase of the year: 1 El Nino, -1 La Nina, 0 neutral
        phase = enso_phases.get(current_date.year, "Neutro")
        instance["enso"] = (
            1 if phase == "El Niño" else (-1 if phase == "La Niña" else 0)
        )

        instances.append(instance)
        current_date += timedelta(days=STEP_DAYS)

    return instances


def process_all_cores(
    points: pd.DataFrame,
    precipitation: pd.DataFrame,
    base_date,
) -> pd.DataFrame:
    """
    Generate the instances for every core and return them as a DataFrame.
    """
    season_start = season_start_of(base_date)
    earliest = season_start + timedelta(days=FLOOR_DAYS)

    # The series only starts on September 1st plus FLOOR_DAYS; before that
    # no core has any row.
    if base_date < earliest:
        raise ValueError(
            f"base_date {base_date:%Y-%m-%d} is earlier than "
            f"{earliest:%Y-%m-%d} (season start plus {FLOOR_DAYS} days)."
        )

    all_instances = []
    for row in points.itertuples(index=False):
        all_instances.extend(generate_instances_for_core(row, precipitation, base_date))

    if not all_instances:
        raise ValueError("No instances generated — check base_date and the input data.")

    return pd.DataFrame(all_instances)


COLUMN_ORDER = [
    "municipio_id",
    "municipio",
    "data",
    "ocorrencia_latitude",
    "ocorrencia_longitude",
    "chuva_dispersao",
    "chuva_pico_intervalo",
    "chuva_pico_valor",
    "chuva_assimetria",
    "chuva_mediana",
    "chuva_mediana_valor",
    "chuva_moda",
    "chuva_moda_valor",
    "prec_acumulada",
    "dias_chuva",
    "dia_da_safra",
    "chuva_coeficiente_variacao",
    "chuva_media",
    "enso",
]


def save_results(df: pd.DataFrame, output_path) -> None:
    """
    Save only the columns the model consumes.
    """
    df[COLUMN_ORDER].to_csv(output_path, index=False, sep=";", encoding="utf-8")
    print(f"{len(df)} instances saved to {output_path}")


def run(
    prec_path: str,
    base_date,
    output_path: str,
) -> str:
    if not isinstance(base_date, (datetime, pd.Timestamp)):
        base_date = pd.to_datetime(base_date)

    municipalities, prec = load_data(prec_path)

    # Drop the geometry before generating instances
    light_cols = [
        "municipio_id",
        "municipio",
        "segment_id",
        "ocorrencia_latitude",
        "ocorrencia_longitude",
    ]
    points = pd.DataFrame(municipalities[light_cols])

    df = process_all_cores(points, prec, base_date)
    save_results(df, output_path)

    return output_path
